name: Release

on:
  push:
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: package
          all-features: true
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: target/package/${{ github.event.inputs.artifact_name }}
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          token: ${{ secrets.CRATES_IO_TOKEN }}
          all-features: true
          manifest-path: target/package/${{ github.event.inputs.artifact_name }}/Cargo.toml
